routes/web.php
<?php

use App\Models\Order;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CampController;
use App\Http\Controllers\CampStatusController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\SponsorShipController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TourController;
use App\Http\Controllers\YearController;

Route::get('/home', function () {
    return redirect()->route('dashboard');
});
Route::get('/', function () {
    return redirect()->route('dashboard');
});


Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('lang/{locale}', [App\Http\Controllers\HomeController::class, 'setLanguage'])->name('setLanguage');

    Route::get('countries', [CountryController::class, 'index'])->name('countries.index');
    Route::post('add-update-country', [CountryController::class, 'store'])->name('add-update-country');
    Route::post('edit-country', [CountryController::class, 'edit'])->name('edit-country');
    Route::get('countries/{id}/destroy', [CountryController::class, 'destroy'])->name('countries.destroy');

    Route::get('camps', [CampController::class, 'index'])->name('camps.index');
    Route::post('add-update-camp', [CampController::class, 'store'])->name('add-update-camp');
    Route::post('edit-camp', [CampController::class, 'edit'])->name('edit-camp');
    Route::get('camps/{id}/destroy', [CampController::class, 'destroy'])->name('camps.destroy');

    Route::get('campStatus', [CampStatusController::class, 'index'])->name('campStatus.index');
    Route::post('add-update-CampStatus', [CampStatusController::class, 'store'])->name('add-update-campStatus');
    Route::post('edit-CampStatus', [CampStatusController::class, 'edit'])->name('edit-campStatus');
    Route::get('campStatus/{id}/destroy', [CampStatusController::class, 'destroy'])->name('campStatus.destroy');

    Route::get('sponsors', [SponsorController::class, 'index'])->name('sponsors.index');
    Route::post('add-update-sponsor', [SponsorController::class, 'store'])->name('add-update-sponsor');
    Route::post('edit-sponsor', [SponsorController::class, 'edit'])->name('edit-sponsor');
    Route::get('sponsors/{id}/destroy', [SponsorController::class, 'destroy'])->name('sponsors.destroy');
//
//
    Route::get('years', [YearController::class, 'index'])->name('years.index');
    Route::post('add-update-year', [YearController::class, 'store'])->name('add-update-year');
    Route::post('edit-year', [YearController::class, 'edit'])->name('edit-year');
    Route::get('years/{id}/destroy', [YearController::class, 'destroy'])->name('years.destroy');
//
    Route::get('tours', [TourController::class, 'index'])->name('tours.index');
    Route::post('add-update-tour', [TourController::class, 'store'])->name('add-update-tour');
    Route::post('edit-tour', [TourController::class, 'edit'])->name('edit-tour');
    Route::get('tours/{id}/destroy', [TourController::class, 'destroy'])->name('tours.destroy');
//
    Route::get('teams', [TeamController::class, 'index'])->name('teams.index');
    Route::post('add-update-team', [TeamController::class, 'store'])->name('add-update-team');
    Route::post('edit-team', [TeamController::class, 'edit'])->name('edit-team');
    Route::get('teams/{id}/destroy', [TeamController::class, 'destroy'])->name('teams.destroy');
//
//    Route::resource('logs', LogController::class);
//
//    Route::get('logs/{id}/destroy', [LogController::class, 'destroy'])->name('logs.destroy');
//
//    Route::resource('settings', App\Http\Controllers\SettingController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
//
    Route::get('sponsorShips', [SponsorShipController::class, 'index'])->name('sponsorShips.index');
    Route::post('add-update-sponsorShip', [SponsorShipController::class, 'store'])->name('add-update-sponsorShip');
    Route::post('edit-sponsorShip', [SponsorShipController::class, 'edit'])->name('edit-sponsorShip');
    Route::get('sponsorShips/{id}/destroy', [SponsorShipController::class, 'destroy'])->name('sponsorShips.destroy');

    Route::resource('plans', App\Http\Controllers\PlanController::class);
    Route::resource('follows', App\Http\Controllers\FollowController::class);


});



use App\Http\Controllers\BookController;
//
//Route::get('ajax-book-crud', [BookController::class, 'index']);
//Route::post('add-update-book', [BookController::class, 'store']);
//Route::post('edit-book', [BookController::class, 'edit']);
//Route::post('delete-book', [BookController::class, 'destroy']);
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
Route::post('generator_builder/generate-from-file', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');

app/Models/Follow.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class Follow
 * @package App\Models
 * @version March 8, 2022, 12:45 am UTC
 *
 * @property integer $camp_id
 * @property integer $camp_status_id
 * @property integer $ending_date
 * @property string $notes
 * @property boolean $status
 * @property string $files
 */
class Follow extends Model
{
    use SoftDeletes;


    public $table = 'follows';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'camp_id',
        'camp_status_id',
        'type',
        'ending_date',
        'notes',
        'status',
        'files'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'camp_id' => 'integer',
        'camp_status_id' => 'integer',

        'notes' => 'string',
        'status' => 'boolean',
        'files' => 'string'
    ];
    public function camp()
    {
        return $this->belongsTo(\App\Models\Camp::class, 'camp_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function campStatus()
    {
        return $this->belongsTo(\App\Models\CampStatus::class, 'camp_status_id', 'id');
    }
    public function getFilesPathAttribute()
    {
        return asset('public/uploads/' . $this->files);

        //   return asset(Storage::url($this->image));



    }
    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [

    ];


}

app/Http/Controllers/FollowController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateFollowRequest;
use App\Http\Requests\UpdateFollowRequest;
use App\Repositories\FollowRepository;
use App\Http\Controllers\AppBaseController;
use App\Traits\ImageTrait;
use Illuminate\Http\Request;
use Flash;
use Response;

class FollowController extends AppBaseController
{
    /** @var  FollowRepository */
    private $followRepository;
use ImageTrait;
    public function __construct(FollowRepository $followRepo)
    {
        $this->followRepository = $followRepo;
    }

    /**
     * Display a listing of the Follow.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $follows = $this->followRepository->paginate(10);

        return view('follows.index')
            ->with('follows', $follows);
    }

    /**
     * Show the form for creating a new Follow.
     *
     * @return Response
     */
    public function create()
    {
        return view('follows.create');
    }

    /**
     * Store a newly created Follow in storage.
     *
     * @param CreateFollowRequest $request
     *
     * @return Response
     */
    public function store(CreateFollowRequest $request)
    {
        $input = $request->all();
   //     dd($request->all());
        if ($request->hasFile('files')) {
            $file_name = $this->savePDF( 'uploads',$request->file('files'));
            $input['files'] = $file_name;
        }
        $input['status'] = $request->status == 'on' ? 1 : 0;
        $follow = $this->followRepository->create($input);


        session()->flash('success', __('site.added_successfully'));

        return redirect(route('follows.index').'?type='.$follow->type);
    }

    /**
     * Display the specified Follow.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $follow = $this->followRepository->find($id);

        if (empty($follow)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('follows.index'));
        }

        return view('follows.show')->with('follow', $follow);
    }

    /**
     * Show the form for editing the specified Follow.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $follow = $this->followRepository->find($id);

        if (empty($follow)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('follows.index').'?type='.request('type'));
        }

        return view('follows.edit')->with('follow', $follow);
    }

    /**
     * Update the specified Follow in storage.
     *
     * @param int $id
     * @param UpdateFollowRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateFollowRequest $request)
    {
        $follow = $this->followRepository->find($id);
        if (empty($follow)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('follows.index'));
        }
        $input = $request->all();
        if ($request->hasFile('files')) {
            $file_name = $this->savePDF( 'uploads',$request->file('files'));
            $input['files'] = $file_name;
        }
        $input['status'] = $request->status == 'on' ? 1 : 0;

        $follow = $this->followRepository->update($input, $id);

        session()->flash('success', __('site.updated_successfully'));

        return redirect(route('follows.index').'?type='.$follow->type);
    }

    /**
     * Remove the specified Follow from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $follow = $this->followRepository->find($id);

        if (empty($follow)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('follows.index'));
        }

        $this->followRepository->delete($id);

        session()->flash('success', __('site.deleted_successfully'));

        return redirect(route('follows.index'));
    }
}

resources/views/follows/create.blade.php
@extends('layouts.app')

@section('style')

    <style>
        .red {
            font-size: 150%;
            border: red solid 3px;
            color: red;
        }
        .download_button {
            margin: 20px;
            text-decoration: none;
            display: block;
            width: 320px;
            height: 110px;
            padding: 1px;
            border: 1px solid #8ebd17;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            border-radius: 10px;
            color: #2a3807;
            text-shadow: 0 0 15px #7da616;
            font-size: 16px;
        }

        .download_button .filename {
            font-size: 32px;
            margin: 10px 20px 0;
        }

        .download_button .filesize {
            margin: 10px 20px 0;
        }

        .download_button .downloads {
            margin: 5px 20px 0;
        }

        .download_button .downloadicon {
            position: relative;
            float: right;
            margin: 10px;
            width: 140px;
            height: 90px;
        }

        @-webkit-keyframes movedown {
            0% {
                -webkit-transform: translateY(-1.5em);
                opacity: 0;
            }
            50% {
                -webkit-transform: translateY(0);
                opacity: 1;
            }
            100% {
                -webkit-transform: translateY(1.5em);
                opacity: 0;
            }
        }

        @-moz-keyframes movedown {
            0% {
                transform: translateY(-1.5em);
                opacity: 0;
            }
            50% {
                transform: translateY(0);
                opacity: 1;
            }
            100% {
                transform: translateY(1.5em);
                opacity: 0;
            }
        }

        @-o-keyframes movedown {
            0% {
                -o-transform: translateY(-1.5em);
                opacity: 0;
            }
            50% {
                -o-transform: translateY(0);
                opacity: 1;
            }
            100% {
                -o-transform: translateY(1.5em);
                opacity: 0;
            }
        }

        @keyframes movedown {
            0% {
                transform: translateY(-1.5em);
                opacity: 0;
            }
            50% {
                transform: translateY(0);
                opacity: 1;
            }
            100% {
                transform: translateY(1.5em);
                opacity: 0;
            }
        }

        .download_button .cloud {
            width: 140px;
            height: 50px;
            background-color: #fff;
            border-radius: 30px;
            position: absolute;
            top: 40px;
        }

        .download_button .cloud:before {
            content: "";
            display: block;
            width: 50px;
            height: 50px;
            top: -30px;
            left: 70px;
            background-color: #fff;
            border-radius: 50%;
            position: absolute;
            box-shadow: -40px 0 0 10px #fff;
        }

        .download_button .cloud .arrowdown {
            background: #aedb3d;
            position: absolute;
            top: -10px;
            left: 60px;
            width: 10px;
            height: 40px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;

            -webkit-animation: movedown 2s infinite linear;
            -moz-animation: movedown 2s infinite linear;
            -o-animation: movedown 2s infinite linear;
            animation: movedown 2s infinite linear;
        }

        .download_button .cloud .arrowdown:before,
        .download_button .cloud .arrowdown:after {
            top: 14px;
            content: "";
            position: absolute;
            background: #aedb3d;
            position: absolute;
            width: 10px;
            height: 25px;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
        }

        .download_button .cloud .arrowdown:before {
            -webkit-transform: rotate(45deg);
            -webkit-transform-origin: 70% 90%;
        }

        .download_button .cloud .arrowdown:after {
            -webkit-transform: rotate(-45deg);
            -webkit-transform-origin: 30% 90%;
        }

        .download_button {

            background: #aedb3d; /* Old browsers */
            background: -moz-linear-gradient(top, #aedb3d 0%, #9fcb31 100%); /* FF3.6+ */
            background: -webkit-gradient(linear, left top, left bottom, color-stop(0%, #aedb3d), color-stop(100%, #9fcb31)); /* Chrome,Safari4+ */
            background: -webkit-linear-gradient(top, #aedb3d 0%, #9fcb31 100%); /* Chrome10+,Safari5.1+ */
            background: -o-linear-gradient(top, #aedb3d 0%, #9fcb31 100%); /* Opera 11.10+ */
            background: -ms-linear-gradient(top, #aedb3d 0%, #9fcb31 100%); /* IE10+ */
            background: linear-gradient(to bottom, #aedb3d 0%, #9fcb31 100%); /* W3C */
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#aedb3d', endColorstr='#9fcb31', GradientType=0); /* IE6-9 */


        }
    </style>
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a href="{{route('follows.index')}}">@lang('site.follows')</a></li>

                        <li class="breadcrumb-item "><a href="{{route('follows.create')}}">@lang('site.add')</a></li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right"
                   href="{{ route('follows.index') }}">
                    @lang('site.follow')
                </a>
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing col-sm-12">

{{--        @include('adminlte-templates::common.errors')--}}

        <div class="card">

            {!! Form::open(['route' => 'follows.store', 'files' => true,'class' =>"needs-validation " ,'novalidate']) !!}

            <div class="card-body">

                <div class="row">
                    @include('follows.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('follows.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

@section('scripts')
    @include('inc.file')
@endsection

resources/views/follows/fields.blade.php
<input type="hidden" value="{{request('type')}}" name="type">

<div class="form-group col-md-4">
    <label>@lang('site.camp')</label>
    <select data-placeholder="@lang('site.camp')" class="form-control basic" name="camp_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.camp')</option>

        @foreach(\App\Models\Camp::get() as $camp)
            <option
                value="{{$camp->id}} "{{@$follow->camp_id == $camp->id||old('camp_id') == $camp->id? 'selected' : '' }} >{{$camp->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('camp_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>
<div class="form-group col-md-4">
    <label>@lang('site.camp_status')</label>
    <select data-placeholder="@lang('site.camp_status')" class="form-control basic" name="camp_status_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.camp_status')</option>

        @foreach(\App\Models\CampStatus::get() as $camp_status)
            <option
                value="{{$camp_status->id}} "{{@$follow->camp_status_id == $camp_status->id||old('camp_status_id') == $camp_status->id? 'selected' : '' }} >{{$camp_status->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('camp_status_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>


<div class="form-group col-sm-4">
    <label>@lang('site.ending_date')</label>
    {!! Form::date('ending_date', @$follow->ending_date, ['class' => 'form-control']) !!}
</div>

<!-- Notes Field -->
<div class="form-group col-sm-10">
    <label>@lang('site.notes')</label>
    {!! Form::text('notes', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group " style="margin-left: -5px;margin-right: -5px">
    <label>@lang('site.status')</label>
    <div class="col-sm-6">
        <label class="switch s-icons s-outline  s-outline-success  mb-8 mr-4">
            <input type="checkbox" name="status" id="status" {{@$follow->status==1?'checked':''}} >

            <span class="slider round"></span>
        </label>
    </div>
</div>



<!-- Image Field -->
<div class="form-group col-sm-6">
    {!! Form::label('files', 'Image:') !!}
    <div class="input-group">
        <div class="custom-file">
            <input type="file" class="custom-file-input" name="files"
                    id="file">
            {!! Form::label('files', 'Choose file', ['class' => 'custom-file-label']) !!}
        </div>
    </div>
</div>
<div class="col-sm-4">
    <div class="form-group col-sm-5">
        @isset($follow)
            <a href="{{@$follow->files_path}}" class="download_button" target="_blank">
                <div class="downloadicon">
                    <div class="cloud">
                        <div class="arrowdown"></div>
                    </div>
                </div>

                <div class="downloads">{{ __('site.download')}} : <span class="value"></span></div>
            </a>
        @endisset
    </div>

</div>

<div class="clearfix"></div>

resources/views/follows/index.blade.php
@extends('layouts.app')
@section('title')
    {{__('site.'.request('type'))}}
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a
                                href="{{route('follows.index').'?type='.request('type')}}">    {{__('site.'.request('type'))}}</a></li>
                    </ol>
                </nav>
            </div>

                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('follows.create').'?type='.request('type') }}">
                        @lang('site.add')
                    </a>
                </div>
        </div>
    </div>


    @include('flash::message')

    <div class="clearfix"></div>


    <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing layout-top-spacing">
        <div class="widget-content widget-content-area ">
            @include('follows.table')


        </div>

    </div>

@endsection

@section('scripts')
    @include('inc.datatables_js')
@endsection

resources/views/follows/show.blade.php
@extends('layouts.app')

@section('style')

@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a
                                href="{{route('follows.index')}}">@lang('site.follows')</a></li>
                        <li class="breadcrumb-item "><a href="#">@lang('site.show')</a></li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right"
                   href="{{ route('follows.index') }}">
                    @lang('site.follow')
                </a>
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing">


        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('follows.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/follows/show_fields.blade.php
<!-- Id Field -->
<div class="col-sm-12">
    {!! Form::label('id', 'Id:') !!}
    <p>{{ $follow->id }}</p>
</div>

<!-- Camp Id Field -->
<div class="col-sm-12">
    {!! Form::label('camp_id', 'Camp Id:') !!}
    <p>{{ $follow->camp_id }}</p>
</div>

<!-- Camp Status Id Field -->
<div class="col-sm-12">
    {!! Form::label('camp_status_id', 'Camp Status Id:') !!}
    <p>{{ $follow->camp_status_id }}</p>
</div>

<!-- Ending Date Field -->
<div class="col-sm-12">
    {!! Form::label('ending_date', 'Ending Date:') !!}
    <p>{{ $follow->ending_date }}</p>
</div>

<!-- Notes Field -->
<div class="col-sm-12">
    {!! Form::label('notes', 'Notes:') !!}
    <p>{{ $follow->notes }}</p>
</div>

<!-- Status Field -->
<div class="col-sm-12">
    {!! Form::label('status', 'Status:') !!}
    <p>{{ $follow->status }}</p>
</div>

<!-- Files Field -->
<div class="col-sm-12">
    {!! Form::label('files', 'Files:') !!}
    <p>{{ $follow->files }}</p>
</div>

<!-- Created At Field -->
<div class="col-sm-12">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $follow->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="col-sm-12">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $follow->updated_at }}</p>
</div>

resources/views/follows/table.blade.php
<div class="table-responsive">
    <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
        <thead>
        <tr>
            <th>#</th>
            <th>@lang('site.type')</th>
            <th>@lang('site.camp')</th>
            <th>@lang('site.campStatus')</th>
            <th>@lang('site.ending_date')</th>
            <th>@lang('site.status')</th>

            <th>@lang('site.action')</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($follows as $x=>$follow)
            <tr id="row_{{$follow->id}}">
                <td>{{ $x+1}}</td>
                <td><div class="td-content product-brand text-secondary">{{ @$follow->type }}</div></td>
                <td><div class="td-content product-brand text-danger">{{ @$follow->camp->name }}</div></td>
                <td><div class="td-content product-brand text-danger">{{ @$follow->campStatus->name }}</div></td>
                <td>{{date('d-m-Y',strtotime($follow->ending_date))  }}</td>
                <td><span class="badge {{$follow->status==1?'badge-success':'badge-danger'}}">{{ $follow->status==1?__('site.active'):__('site.inActive') }}</span>

                <td class="text-center">

                    <ul class="table-controls">
                        <li><a href="{{ route('follows.edit',$follow->id).'?type='.request('type')}}" data-id="{{ $follow->id }}" class="bs-tooltip edit"
                               title="@lang('site.edit') ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                     stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round"
                                     class="feather feather-check-circle text-primary">
                                    <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                                    <polyline points="22 4 12 14.01 9 11.01"></polyline>
                                </svg>
                            </a></li>
                        <li><a href="#"
                               onclick="sweet_delete( ' {{ route('follows.destroy',$follow->id) }} ' , '{{ trans('site.confirm_delete') }}' ,{{ $follow->id }} )"
                               class="bs-tooltip" title="@lang('site.delete') ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                     stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round"
                                     class="feather feather-x-circle text-danger">
                                    <circle cx="12" cy="12" r="10"></circle>
                                    <line x1="15" y1="9" x2="9" y2="15"></line>
                                    <line x1="9" y1="9" x2="15" y2="15"></line>
                                </svg>
                            </a></li>

                    </ul>


                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>