routes/web.php
<?php

use App\Models\Order;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CampController;
use App\Http\Controllers\CampStatusController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\SponsorShipController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TourController;
use App\Http\Controllers\YearController;

Route::get('/home', function () {
    return redirect()->route('dashboard');
});
Route::get('/', function () {
    return redirect()->route('dashboard');
});


Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('lang/{locale}', [App\Http\Controllers\HomeController::class, 'setLanguage'])->name('setLanguage');

    Route::get('countries', [CountryController::class, 'index'])->name('countries.index');
    Route::post('add-update-country', [CountryController::class, 'store'])->name('add-update-country');
    Route::post('edit-country', [CountryController::class, 'edit'])->name('edit-country');
    Route::get('countries/{id}/destroy', [CountryController::class, 'destroy'])->name('countries.destroy');

    Route::get('camps', [CampController::class, 'index'])->name('camps.index');
    Route::post('add-update-camp', [CampController::class, 'store'])->name('add-update-camp');
    Route::post('edit-camp', [CampController::class, 'edit'])->name('edit-camp');
    Route::get('camps/{id}/destroy', [CampController::class, 'destroy'])->name('camps.destroy');

    Route::get('campStatus', [CampStatusController::class, 'index'])->name('campStatus.index');
    Route::post('add-update-CampStatus', [CampStatusController::class, 'store'])->name('add-update-campStatus');
    Route::post('edit-CampStatus', [CampStatusController::class, 'edit'])->name('edit-campStatus');
    Route::get('campStatus/{id}/destroy', [CampStatusController::class, 'destroy'])->name('campStatus.destroy');

    Route::get('sponsors', [SponsorController::class, 'index'])->name('sponsors.index');
    Route::post('add-update-sponsor', [SponsorController::class, 'store'])->name('add-update-sponsor');
    Route::post('edit-sponsor', [SponsorController::class, 'edit'])->name('edit-sponsor');
    Route::get('sponsors/{id}/destroy', [SponsorController::class, 'destroy'])->name('sponsors.destroy');
//
//
    Route::get('years', [YearController::class, 'index'])->name('years.index');
    Route::post('add-update-year', [YearController::class, 'store'])->name('add-update-year');
    Route::post('edit-year', [YearController::class, 'edit'])->name('edit-year');
    Route::get('years/{id}/destroy', [YearController::class, 'destroy'])->name('years.destroy');
//
    Route::get('tours', [TourController::class, 'index'])->name('tours.index');
    Route::post('add-update-tour', [TourController::class, 'store'])->name('add-update-tour');
    Route::post('edit-tour', [TourController::class, 'edit'])->name('edit-tour');
    Route::get('tours/{id}/destroy', [TourController::class, 'destroy'])->name('tours.destroy');
//
    Route::get('teams', [TeamController::class, 'index'])->name('teams.index');
    Route::post('add-update-team', [TeamController::class, 'store'])->name('add-update-team');
    Route::post('edit-team', [TeamController::class, 'edit'])->name('edit-team');
    Route::get('teams/{id}/destroy', [TeamController::class, 'destroy'])->name('teams.destroy');
//
//    Route::resource('logs', LogController::class);
//
//    Route::get('logs/{id}/destroy', [LogController::class, 'destroy'])->name('logs.destroy');
//
//    Route::resource('settings', App\Http\Controllers\SettingController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
//
    Route::get('sponsorShips', [SponsorShipController::class, 'index'])->name('sponsorShips.index');
    Route::post('add-update-sponsorShip', [SponsorShipController::class, 'store'])->name('add-update-sponsorShip');
    Route::post('edit-sponsorShip', [SponsorShipController::class, 'edit'])->name('edit-sponsorShip');
    Route::get('sponsorShips/{id}/destroy', [SponsorShipController::class, 'destroy'])->name('sponsorShips.destroy');

    Route::resource('plans', App\Http\Controllers\PlanController::class);
    Route::resource('follows', App\Http\Controllers\FollowController::class);


});



use App\Http\Controllers\BookController;
//
//Route::get('ajax-book-crud', [BookController::class, 'index']);
//Route::post('add-update-book', [BookController::class, 'store']);
//Route::post('edit-book', [BookController::class, 'edit']);
//Route::post('delete-book', [BookController::class, 'destroy']);
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
Route::post('generator_builder/generate-from-file', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');

resources/views/admin/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                            </li>
{{--                            <li class="breadcrumb-item "><a--}}
{{--                                    href="{{route('users.edit',$user->id)}}">@lang('site.edit')</a>--}}
{{--                            </li>--}}
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
{{--                <a class="btn btn-primary float-right"--}}
{{--                   href="{{ route('users.create') }}">--}}
{{--                    @lang('site.add')--}}
{{--                </a>--}}
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing col-sm-12">

        @include('adminlte-templates::common.errors')

        <div class="card">

            <form action="{{route('admin.update')}}" method="post" enctype="multipart/form-data" class ="needs-validation"  novalidate >

                {{ csrf_field() }}
                {{ method_field('post') }}
                <div class="card-body">
                    <div class="row">



                        <div class="form-group col-sm-6">
                            <label>@lang('site.Salt')</label>
                            <input type="text" name="Salt" class="form-control" value="{{  $user->Salt  }}" aria-describedby="inputGroupPrepend" required>
                            <span class="invalid-feedback">@lang('site.required')</span>
                        </div>

                        <div class="form-group col-sm-6">
                            <label>@lang('site.Email')</label>
                            <input type="email" name="Email" class="form-control" value="{{ $user->Email }}" aria-describedby="inputGroupPrepend" required>
                            <span class="invalid-feedback">@lang('site.email_valid')</span>
                        </div>


                        <div class="form-group col-md-6">
                            <label>@lang('site.password')</label>
                            <input type="password" name="password" class="form-control" autocomplete="new-password" aria-describedby="inputGroupPrepend"  minlength="6">
                            <span class="invalid-feedback">@lang('site.password_valid')</span>
                        </div>

                        <div class="form-group col-md-6">
                            <label>@lang('site.password_confirmation')</label>
                            <input type="password" name="password_confirmation" class="form-control"  id="confirmPassword"  >
                        </div>
                    </div>
                </div>


                <div class="card-footer">
                    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
{{--                    <a href="{{ route('users.index') }}" class="btn btn-default">Cancel</a>--}}
                </div>

            </form><!-- end of form -->

        </div>
    </div>
@endsection
@section('scripts')
    @include('inc.file')
@endsection

resources/views/admin/show.blade.php
@extends('layouts.app')

@section('style')

@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a
                                href="{{route('users.index')}}">@lang('site.users')</a></li>
                        <li class="breadcrumb-item "><a href="#">@lang('site.show')</a></li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right"
                   href="{{ route('users.index') }}">
                    @lang('site.vendor')
                </a>
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing">


        <div class="card">
            <div class="card-body">
                <div class="row">
                    @include('users.show_fields')
                </div>
            </div>
        </div>
    </div>
@endsection