routes/web.php
<?php

use App\Models\Order;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\LogController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\CampController;
use App\Http\Controllers\CampStatusController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\SponsorShipController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\TourController;
use App\Http\Controllers\YearController;

Route::get('/home', function () {
    return redirect()->route('dashboard');
});
Route::get('/', function () {
    return redirect()->route('dashboard');
});


Auth::routes();

Route::group(['prefix' => 'dashboard', 'middleware' => 'auth'], function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'dashboard'])->name('dashboard');
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    Route::get('lang/{locale}', [App\Http\Controllers\HomeController::class, 'setLanguage'])->name('setLanguage');

    Route::get('countries', [CountryController::class, 'index'])->name('countries.index');
    Route::post('add-update-country', [CountryController::class, 'store'])->name('add-update-country');
    Route::post('edit-country', [CountryController::class, 'edit'])->name('edit-country');
    Route::get('countries/{id}/destroy', [CountryController::class, 'destroy'])->name('countries.destroy');

    Route::get('camps', [CampController::class, 'index'])->name('camps.index');
    Route::post('add-update-camp', [CampController::class, 'store'])->name('add-update-camp');
    Route::post('edit-camp', [CampController::class, 'edit'])->name('edit-camp');
    Route::get('camps/{id}/destroy', [CampController::class, 'destroy'])->name('camps.destroy');

    Route::get('campStatus', [CampStatusController::class, 'index'])->name('campStatus.index');
    Route::post('add-update-CampStatus', [CampStatusController::class, 'store'])->name('add-update-campStatus');
    Route::post('edit-CampStatus', [CampStatusController::class, 'edit'])->name('edit-campStatus');
    Route::get('campStatus/{id}/destroy', [CampStatusController::class, 'destroy'])->name('campStatus.destroy');

    Route::get('sponsors', [SponsorController::class, 'index'])->name('sponsors.index');
    Route::post('add-update-sponsor', [SponsorController::class, 'store'])->name('add-update-sponsor');
    Route::post('edit-sponsor', [SponsorController::class, 'edit'])->name('edit-sponsor');
    Route::get('sponsors/{id}/destroy', [SponsorController::class, 'destroy'])->name('sponsors.destroy');
//
//
    Route::get('years', [YearController::class, 'index'])->name('years.index');
    Route::post('add-update-year', [YearController::class, 'store'])->name('add-update-year');
    Route::post('edit-year', [YearController::class, 'edit'])->name('edit-year');
    Route::get('years/{id}/destroy', [YearController::class, 'destroy'])->name('years.destroy');
//
    Route::get('tours', [TourController::class, 'index'])->name('tours.index');
    Route::post('add-update-tour', [TourController::class, 'store'])->name('add-update-tour');
    Route::post('edit-tour', [TourController::class, 'edit'])->name('edit-tour');
    Route::get('tours/{id}/destroy', [TourController::class, 'destroy'])->name('tours.destroy');
//
    Route::get('teams', [TeamController::class, 'index'])->name('teams.index');
    Route::post('add-update-team', [TeamController::class, 'store'])->name('add-update-team');
    Route::post('edit-team', [TeamController::class, 'edit'])->name('edit-team');
    Route::get('teams/{id}/destroy', [TeamController::class, 'destroy'])->name('teams.destroy');
//
//    Route::resource('logs', LogController::class);
//
//    Route::get('logs/{id}/destroy', [LogController::class, 'destroy'])->name('logs.destroy');
//
//    Route::resource('settings', App\Http\Controllers\SettingController::class);
    Route::resource('users', App\Http\Controllers\UserController::class);
//
    Route::get('sponsorShips', [SponsorShipController::class, 'index'])->name('sponsorShips.index');
    Route::post('add-update-sponsorShip', [SponsorShipController::class, 'store'])->name('add-update-sponsorShip');
    Route::post('edit-sponsorShip', [SponsorShipController::class, 'edit'])->name('edit-sponsorShip');
    Route::get('sponsorShips/{id}/destroy', [SponsorShipController::class, 'destroy'])->name('sponsorShips.destroy');

    Route::resource('plans', App\Http\Controllers\PlanController::class);
    Route::resource('follows', App\Http\Controllers\FollowController::class);


});



use App\Http\Controllers\BookController;
//
//Route::get('ajax-book-crud', [BookController::class, 'index']);
//Route::post('add-update-book', [BookController::class, 'store']);
//Route::post('edit-book', [BookController::class, 'edit']);
//Route::post('delete-book', [BookController::class, 'destroy']);
Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder')->name('io_generator_builder');
Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate')->name('io_field_template');
Route::get('relation_field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@relationFieldTemplate')->name('io_relation_field_template');
Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate')->name('io_generator_builder_generate');
Route::post('generator_builder/rollback', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@rollback')->name('io_generator_builder_rollback');
Route::post('generator_builder/generate-from-file', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generateFromFile')->name('io_generator_builder_generate_from_file');

app/Models/Plan.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;


/**
 * Class Plan
 * @package App\Models
 * @version March 6, 2022, 1:15 am UTC
 *
 * @property \App\Models\Tour $tour
 * @property \App\Models\Year $year
 * @property \App\Models\Camp $camp
 * @property \App\Models\CampStatus $campStatus
 * @property \App\Models\Sponsor $sponsor
 * @property \App\Models\SponsorShip $sponsorShip
 * @property integer $year_id
 * @property integer $tour_id
 * @property integer $country_id
 * @property integer $camp_id
 * @property integer $team_id
 * @property integer $sponsor_id
 * @property integer $camp_status_id
 * @property integer $sponsor_ship_id
 * @property string $from
 * @property string $to
 * @property string $notes
 * @property boolean $need_follow_up
 * @property string $type
 */
class Plan extends Model
{
    use SoftDeletes;


    public $table = 'plans';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'year_id',
        'tour_id',
        'country_id',
        'camp_id',
        'team_id',
        'sponsor_id',
        'camp_status_id',
        'sponsor_ship_id',
        'from',
        'to',
        'notes',
        'need_follow_up',
        'type'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'year_id' => 'integer',
        'tour_id' => 'integer',
        'country_id' => 'integer',
        'camp_id' => 'integer',
        'team_id' => 'integer',
        'sponsor_id' => 'integer',
        'camp_status_id' => 'integer',
        'sponsor_ship_id' => 'integer',
        'from' => 'date',
        'to' => 'date',
        'notes' => 'string',
        'need_follow_up' => 'boolean',
        'type' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'year_id' => 'required',
        'tour_id' => 'required',
        'country_id' => 'required',
        'camp_id' => 'required',
        'team_id' => 'required',
        'sponsor_id' => 'required',
        'camp_status_id' => 'required',
        'sponsor_ship_id' => 'required',
        'from' => 'required',
        'to' => 'required'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function tour()
    {
        return $this->belongsTo(\App\Models\Tour::class, 'tour_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function year()
    {
        return $this->belongsTo(\App\Models\Year::class, 'year_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function camp()
    {
        return $this->belongsTo(\App\Models\Camp::class, 'camp_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function campStatus()
    {
        return $this->belongsTo(\App\Models\CampStatus::class, 'camp_status_id', 'id');
    }
    public function country()
    {
        return $this->belongsTo(\App\Models\Country::class, 'country_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function sponsor()
    {
        return $this->belongsTo(\App\Models\Sponsor::class, 'sponsor_id', 'id');
    }
    public function team()
    {
        return $this->belongsTo(\App\Models\Team::class, 'team_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function sponsorShip()
    {
        return $this->belongsTo(\App\Models\SponsorShip::class, 'sponsor_ship_id', 'id');
    }
//    public function getNameAttribute()
//    {
//        if (app()->getLocale() == 'ar') {
//            return $this->name_ar;
//        } else {
//            return $this->name_en;
//
//        }
//
//    }
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePlanRequest;
use App\Http\Requests\UpdatePlanRequest;
use App\Repositories\PlanRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class PlanController extends AppBaseController
{
    /** @var  PlanRepository */
    private $planRepository;

    public function __construct(PlanRepository $planRepo)
    {
        $this->planRepository = $planRepo;
    }

    /**
     * Display a listing of the Plan.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $plans = $this->planRepository->paginate(10);

        return view('plans.index')
            ->with('plans', $plans);
    }

    /**
     * Show the form for creating a new Plan.
     *
     * @return Response
     */
    public function create()
    {
        return view('plans.create');
    }

    /**
     * Store a newly created Plan in storage.
     *
     * @param CreatePlanRequest $request
     *
     * @return Response
     */
    public function store(CreatePlanRequest $request)
    {
        $input = $request->all();
        $input['need_follow_up'] = $request->need_follow_up == 'on' ? 1 : 0;

        $plan = $this->planRepository->create($input);

        session()->flash('success', __('site.added_successfully'));

        return redirect(route('plans.index'));
    }

    /**
     * Display the specified Plan.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $plan = $this->planRepository->find($id);

        if (empty($plan)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('plans.index'));
        }

        return view('plans.show')->with('plan', $plan);
    }

    /**
     * Show the form for editing the specified Plan.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $plan = $this->planRepository->find($id);

        if (empty($plan)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('plans.index'));
        }

        return view('plans.edit')->with('plan', $plan);
    }

    /**
     * Update the specified Plan in storage.
     *
     * @param int $id
     * @param UpdatePlanRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePlanRequest $request)
    {
        $plan = $this->planRepository->find($id);

        if (empty($plan)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('plans.index'));
        }
        $input=$request->all();
        $input['need_follow_up'] = $request->need_follow_up == 'on' ? 1 : 0;

        $plan = $this->planRepository->update($input, $id);

        session()->flash('success', __('site.updated_successfully'));

        return redirect(route('plans.index'));
    }

    /**
     * Remove the specified Plan from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $plan = $this->planRepository->find($id);

        if (empty($plan)) {
            session()->flash('error', __('site.not_found'));

            return redirect(route('plans.index'));
        }

        $this->planRepository->delete($id);

        session()->flash('success', __('site.deleted_successfully'));

        return redirect(route('plans.index'));
    }
}

resources/views/plans/create.blade.php
@extends('layouts.app')

@section('style')

@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a href="{{route('plans.index')}}">@lang('site.plans')</a></li>
                        <li class="breadcrumb-item "><a href="{{route('plans.create')}}">@lang('site.add')</a></li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right"
                   href="{{ route('plans.index') }}">
                    @lang('site.plan')
                </a>
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing">

{{--        @include('adminlte-templates::common.errors')--}}

        <div class="card">

            {!! Form::open(['route' => 'plans.store', 'files' => true,'class' =>"needs-validation " ,'novalidate']) !!}

            <div class="card-body">

                <div class="row">
                    @include('plans.fields')
                </div>

            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('plans.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection

@section('scripts')
    @include('inc.file')
@endsection

resources/views/plans/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a
                                href="{{route('plans.index')}}">@lang('site.plans')</a></li>
                        <li class="breadcrumb-item "><a
                                href="{{route('plans.edit',$plan->id)}}">@lang('site.edit')</a></li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-6">
                <a class="btn btn-primary float-right"
                   href="{{ route('plans.index') }}">
                    @lang('site.plan')
                </a>
            </div>
        </div>
    </div>


    <div class="content px-3 layout-top-spacing">

        {{--        @include('adminlte-templates::common.errors')--}}

        <div class="card">

            {!! Form::model($plan, ['route' => ['plans.update', $plan->id], 'method' => 'patch', 'files' => true ,'class' =>"needs-validation " ,'novalidate']) !!}

            <div class="card-body">
                <div class="row">
                    @include('plans.fields')
                </div>
            </div>

            <div class="card-footer">
                {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
                <a href="{{ route('plans.index') }}" class="btn btn-default">Cancel</a>
            </div>

            {!! Form::close() !!}

        </div>
    </div>
@endsection
@section('scripts')
    @include('inc.file')
@endsection

resources/views/plans/fields.blade.php
<div class="form-group col-md-6">
    <label>@lang('site.year')</label>
    <select data-placeholder="@lang('site.year')" class="form-control basic" name="year_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.year')</option>

        @foreach(\App\Models\Year::get() as $year)
            <option
                value="{{$year->id}} "{{@$plan->year_id == $year->id||old('year_id') == $year->id? 'selected' : '' }} >{{$year->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('year_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>
<!-- tour Id Field -->
<div class="form-group col-md-6">
    <label>@lang('site.tour')</label>
    <select data-placeholder="@lang('site.tour')" class="form-control basic" name="tour_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.tour')</option>

        @foreach(\App\Models\Tour::get() as $tour)
            <option
                value="{{$tour->id}} "{{@$plan->tour_id == $tour->id||old('tour_id') == $tour->id? 'selected' : '' }} >{{$tour->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('tour_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>

<div class="form-group col-md-6">
    <label>@lang('site.country')</label>
    <select data-placeholder="@lang('site.country')" class="form-control basic" name="country_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.country')</option>

        @foreach(\App\Models\Country::get() as $country)
            <option
                value="{{$country->id}} "{{@$plan->country_id == $country->id||old('country_id') == $country->id? 'selected' : '' }} >{{$country->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('country_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>


<div class="form-group col-md-6">
    <label>@lang('site.camp')</label>
    <select data-placeholder="@lang('site.camp')" class="form-control basic" name="camp_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.camp')</option>

        @foreach(\App\Models\Camp::get() as $camp)
            <option
                value="{{$camp->id}} "{{@$plan->camp_id == $camp->id||old('camp_id') == $camp->id? 'selected' : '' }} >{{$camp->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('camp_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>
<div class="form-group col-md-6">
    <label>@lang('site.team')</label>
    <select data-placeholder="@lang('site.team')" class="form-control basic" name="team_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.team')</option>

        @foreach(\App\Models\Team::get() as $team)
            <option
                value="{{$team->id}} "{{@$plan->team_id == $team->id||old('team_id') == $team->id? 'selected' : '' }} >{{$team->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('team_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>

<div class="form-group col-md-6">
    <label>@lang('site.sponsor')</label>
    <select data-placeholder="@lang('site.sponsor')" class="form-control basic" name="sponsor_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.sponsor')</option>

        @foreach(\App\Models\Sponsor::get() as $sponsor)
            <option
                value="{{$sponsor->id}} "{{@$plan->sponsor_id == $sponsor->id||old('sponsor_id') == $sponsor->id? 'selected' : '' }} >{{$sponsor->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('sponsor_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>

<div class="form-group col-md-6">
    <label>@lang('site.camp_status')</label>
    <select data-placeholder="@lang('site.camp_status')" class="form-control basic" name="camp_status_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.camp_status')</option>

        @foreach(\App\Models\CampStatus::get() as $camp_status)
            <option
                value="{{$camp_status->id}} "{{@$plan->camp_status_id == $camp_status->id||old('camp_status_id') == $camp_status->id? 'selected' : '' }} >{{$camp_status->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('camp_status_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>
<div class="form-group col-md-6">
    <label>@lang('site.sponsor_ship')</label>
    <select data-placeholder="@lang('site.sponsor_ship')" class="form-control basic" name="sponsor_ship_id"
            aria-describedby="inputGroupPrepend" required>
        <option value="">@lang('site.sponsor_ship')</option>

        @foreach(\App\Models\SponsorShip::get() as $sponsor_ship)
            <option
                value="{{$sponsor_ship->id}} "{{@$plan->sponsor_ship_id == $sponsor_ship->id||old('sponsor_ship_id') == $sponsor_ship->id? 'selected' : '' }} >{{$sponsor_ship->name}}</option>
        @endforeach

    </select>
    <span class="invalid-feedback">@lang('site.required')</span>

    @error('sponsor_ship_id')<span class="text-danger">{{ $message }}</span>@enderror

</div>

<!-- From Field -->
<div class="form-group col-sm-6">
    <label for="from">@lang('site.from')</label>
    {!! Form::date('from', @$plan->from, ['class' => 'form-control']) !!}
</div>

<!-- To Field -->
<div class="form-group col-sm-6">
    <label>@lang('site.to')</label>
    {!! Form::date('to', @$plan->to, ['class' => 'form-control']) !!}
</div>

<!-- Notes Field -->
<div class="form-group col-sm-10">
    <label>@lang('site.notes')</label>
    {!! Form::text('notes', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group " style="margin-left: -5px;margin-right: -5px">
    <label>@lang('site.need_follow_up')</label>
    <div class="col-sm-6">
        <label class="switch s-icons s-outline  s-outline-success  mb-8 mr-4">
            <input type="checkbox" name="need_follow_up" id="status" {{@$plan->need_follow_up==1?'checked':''}} >

            <span class="slider round"></span>
        </label>
    </div>
</div>

{{--<!-- Type Field -->--}}
{{--<div class="form-group col-sm-6">--}}
{{--    {!! Form::label('type', 'Type:') !!}--}}
{{--    {!! Form::text('type', null, ['class' => 'form-control']) !!}--}}
{{--</div>--}}

resources/views/plans/index.blade.php
@extends('layouts.app')
@section('title')
    @lang('site.plans')
@endsection
@section('content')
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <nav class="breadcrumb-two" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}">@lang('site.dashboard')</a></li>
                        <li class="breadcrumb-item active"><a
                                href="{{route('plans.index')}}">@lang('site.plans')</a></li>
                    </ol>
                </nav>
            </div>
            @if (auth()->user()->hasPermission('create_plans')&&auth()->user()->type!='customer_service')

                <div class="col-sm-6">
                    <a class="btn btn-primary float-right"
                       href="{{ route('plans.create') }}">
                        @lang('site.add')
                    </a>
                </div>
            @endif
        </div>
    </div>


    @include('flash::message')

    <div class="clearfix"></div>


    <div class="col-xl-12 col-lg-12 col-sm-12  layout-spacing layout-top-spacing">
        <div class="widget-content widget-content-area ">
            @include('plans.table')


        </div>

    </div>

@endsection

@section('scripts')
    @include('inc.datatables_js')
@endsection

resources/views/plans/table.blade.php
<div class="table-responsive">
    <table id="html5-extension" class="table table-hover non-hover" style="width:100%">
        <thead>
        <tr>
            <th>@lang('site.year')</th>
            <th>@lang('site.tour')</th>
            <th>@lang('site.country')</th>
            <th> @lang('site.camp')</th>
            <th> @lang('site.camp_status')</th>
            <th>@lang('site.team')</th>
            <th>@lang('site.sponsor')</th>
            <th>@lang('site.action')</th>
        </tr>
        </thead>
        <tbody>


        @foreach($plans as $index=>$plan)
            <tr id="row_{{$plan->id}}">
                <td class="text-center"><span class="td-content product-brand text-danger">{{ @$plan->year->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-warning">{{ @$plan->tour->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-warning">{{ @$plan->country->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-primary">{{ @$plan->campStatus->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-primary">{{ @$plan->camp->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-danger">{{ @$plan->team->name }}</span></td>
                <td class="text-center"><span class="td-content product-brand text-danger">{{ @$plan->sponsor->name }}</span></td>

                <td class="text-center">

                    <ul class="table-controls">
                        <li><a href="{{ route('plans.show', $plan->id) }}" class="bs-tooltip"
                               title="@lang('site.show') ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                     viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                     stroke-width="2" stroke-linecap="round"
                                     stroke-linejoin="round"
                                     class="feather feather-eye text-danger">
                                    <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                                    <circle cx="12" cy="12" r="3"></circle>
                                </svg>
                            </a></li>
                            <li><a href="{{ route('plans.edit', $plan->id) }}" class="bs-tooltip"
                                   title="@lang('site.edit') ">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-check-circle text-primary">
                                        <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path>
                                        <polyline points="22 4 12 14.01 9 11.01"></polyline>
                                    </svg>
                                </a></li>
                            <li><a href="#"
                                   onclick="sweet_delete( ' {{ route('plans.destroy',$plan->id) }} ' , '{{ trans('site.confirm_delete') }}' ,{{ $plan->id }} )"
                                   class="bs-tooltip" title="@lang('site.delete') ">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24"
                                         viewBox="0 0 24 24" fill="none" stroke="currentColor"
                                         stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round"
                                         class="feather feather-x-circle text-danger">
                                        <circle cx="12" cy="12" r="10"></circle>
                                        <line x1="15" y1="9" x2="9" y2="15"></line>
                                        <line x1="9" y1="9" x2="15" y2="15"></line>
                                    </svg>
                                </a></li>
                    </ul>


                </td>
            </tr>
        @endforeach
        </tbody>
        <tfoot>
        <tr>

            <th>@lang('site.year')</th>
            <th>@lang('site.tour')</th>
            <th>@lang('site.country')</th>
            <th> @lang('site.camp')</th>
            <th> @lang('site.camp_status')</th>
            <th>@lang('site.team')</th>
            <th>@lang('site.sponsor')</th>
            <th style="visibility: hidden">#</th>

        </tr>
        </tfoot>
    </table>

</div>